[project]
name = "mlops-exoplanet-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["asyncpg>=0.31.0", "fastapi>=0.141.1", "uvicorn>=0.53.0"]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.8",
]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "BLE"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
